### ISSUE TITLE
Is there a way to open the server console?

### ISSUE THREAD

**Issue by lyleaigbedion** [Cirvante/docker-srb2kart#1]
I want to run the server console and poke around with some commands that work with the server. Is there anyway to use docker-compose exec to access it?

**Comment by lyleaigbedion** [comment]
Ignore my second question I didn't read enough of the files >_<

**Comment by Cirvante** [comment]
Commit 96de1d5 resolves this issue.

You should now be able to use `docker attach <container-name>` to attach to the server tty console. Console command history should also show up in the docker logs for the container.

To detach from the console, press Ctrl-P Ctrl-Q.
