### ISSUE TITLE
Addon Order

### ISSUE THREAD

**Issue by lyleaigbedion** [Cirvante/docker-srb2kart#2]
I have some mods/addons that I want to use but they depend on other mods and addons to be installed first. how can I guarantee installation order?

**Comment by Cirvante** [comment]
Commit 96de1d5 resolves this issue.

The server launcher script now supports specifying a priority.cfg file which will guarantee the loading order.

The format of the priority.cfg file should be a text file with one WAD filename per line (just the base filename plus extension, not the full path - kinda like remlines)

e.g.:

kbl_battleplus_v1.1H.pk3
KL_HOSTMOD_V16.pk3
...

These WADs will be inserted into the -wads parameter in the srb2kart command in the exact order they appear in the priority.cfg file. Any incorrect filenames are simply ignored, so mind your spelling!
